export type StatsRow = {
  identity: {
    type: "human" | "bot";
    authUserId?: string;
    characterId?: string;
    name: string;
  };
  gamesPlayed: number;
  gamesWon: number;
  winRate: number;
  netChips: number;
  totalChipsWon: number;
  totalChipsLost: number;
  bestChipFinish: number;
  showdownsReached: number;
  showdownsWon: number;
  totalWords: number;
  avgWordScore: number;
  bestWord: string | null;
  bestWordScore: number;
  longestWord: string | null;
  recentWords: Array<{ word: string; score: number; createdAt: number }>;
  totalChecks: number;
  totalCalls: number;
  totalRaises: number;
  totalFolds: number;
  foldPercent: number;
  vpip: number;
  aggressionFactor: number;
  foldsByStage: { preflop: number; flop: number; turn: number; final: number };
  totalBluffs?: number;
  totalFallbacks?: number;
  bluffRate?: number;
  fallbackRate?: number;
  avgLatencyMs?: number;
  avgHandStrength?: number;
  totalAiDecisions?: number;
  totalAiSuccesses?: number;
  totalAiFailures?: number;
  lastGameAt: number;
};
