// game-engine.jsx — Word Poker game logic + dictionary

const LETTER_VALUES = {
  A:1,E:1,I:1,O:1,U:1,
  R:2,S:2,T:2,L:2,N:2,
  D:3,G:3,
  B:4,C:4,M:4,P:4,
  F:5,H:5,V:5,W:5,Y:5,K:5,
  J:8,X:8,
  Q:10,Z:10,
};

// frequency-weighted letter bag (loosely scrabble-like)
const LETTER_BAG = (
  'A'.repeat(9) + 'B'.repeat(2) + 'C'.repeat(2) + 'D'.repeat(4) +
  'E'.repeat(12) + 'F'.repeat(2) + 'G'.repeat(3) + 'H'.repeat(2) +
  'I'.repeat(9) + 'J'.repeat(1) + 'K'.repeat(1) + 'L'.repeat(4) +
  'M'.repeat(2) + 'N'.repeat(6) + 'O'.repeat(8) + 'P'.repeat(2) +
  'Q'.repeat(1) + 'R'.repeat(6) + 'S'.repeat(4) + 'T'.repeat(6) +
  'U'.repeat(4) + 'V'.repeat(2) + 'W'.repeat(2) + 'X'.repeat(1) +
  'Y'.repeat(2) + 'Z'.repeat(1)
).split('');

const CHOICE_PAIRS = [
  ['A','E'],['E','I'],['O','U'],['A','I'],
  ['T','S'],['R','N'],['D','T'],['S','L'],
  ['Q','K'],['Z','X'],['J','H'],
];

// A curated small dictionary — enough for a believable demo.
// Focus on 2-7 letter common words. (Real game would use TWL/SOWPODS.)
const DICT = new Set((
  // 2-letter
  'AA AB AD AE AG AH AI AL AM AN AR AS AT AW AX AY '+
  'BA BE BI BO BY DE DO ED EF EH EL EM EN ER ES ET EX '+
  'FA FE GO HA HE HI HM HO ID IF IN IS IT JO KA LA LI LO MA ME MI MM MO MU MY '+
  'NA NE NO NU OD OE OF OH OI OM ON OP OR OS OW OX OY PA PE PI PO QI '+
  'RE SH SI SO TA TI TO UH UM UN UP US UT WE WO XI XU YA YE YO ZA '+
  // 3-letter
  'ACE ACT ADD AGE AGO AID AIM AIR ALE ALL AND ANT ANY APE APT ARC ARE ARK ARM ART ASH ASK AWE AXE '+
  'BAD BAG BAR BAT BAY BED BEE BEG BET BID BIG BIN BIT BOA BOB BOG BOO BOW BOX BOY BUD BUG BUN BUS BUT BUY BYE '+
  'CAB CAN CAP CAR CAT COG CON COO COP COT COW COY CRY CUB CUE CUP CUR CUT '+
  'DAB DAD DAM DAY DEN DEW DID DIE DIG DIM DIN DIP DOE DOG DON DOT DRY DUB DUE DUG DYE '+
  'EAR EAT EBB EEL EGG EGO ELF ELK ELM END ERA ERR EVE EWE EYE '+
  'FAD FAN FAR FAT FAX FED FEE FEN FEW FIB FIG FIN FIR FIT FIX FLU FLY FOE FOG FOR FOX FRY FUN FUR '+
  'GAG GAL GAP GAS GAY GEE GEL GEM GET GIG GIN GOD GOO GOT GUM GUN GUT GUY GYM '+
  'HAD HAG HAM HAS HAT HAY HEM HEN HER HEW HEX HEY HID HIM HIP HIS HIT HOB HOE HOG HOP HOT HOW HUB HUE HUG HUM HUT '+
  'ICE ICY ILL IMP INK INN ION IRE IRK ITS IVY '+
  'JAB JAM JAR JAW JAY JET JIG JOB JOG JOT JOY JUG JUT '+
  'KEG KEN KEY KID KIN KIT '+
  'LAB LAD LAG LAP LAW LAX LAY LED LEE LEG LET LID LIE LIP LIT LOB LOG LOO LOP LOT LOW LUG '+
  'MAD MAN MAP MAR MAT MAW MAY MEN MET MEW MID MIX MOB MOD MOM MOO MOP MOW MUD MUG '+
  'NAB NAG NAP NAY NET NEW NIB NIL NIP NOD NOR NOT NOW NUB NUN NUT '+
  'OAK OAR OAT ODD ODE OFF OFT OIL OLD ONE OPT ORB ORE OUR OUT OVA OWE OWL OWN '+
  'PAD PAN PAR PAT PAW PAY PEA PEG PEN PEP PER PET PEW PIE PIG PIN PIT PLY POD POI POP POT POW PRO PRY PUB PUG PUN PUP PUT '+
  'RAG RAJ RAM RAN RAP RAT RAW RAY RED REF RIB RID RIG RIM RIP ROB ROD ROE ROT ROW RUB RUE RUG RUM RUN RUT RYE '+
  'SAD SAG SAP SAT SAW SAY SEA SEE SET SEW SHE SHH SHY SIN SIP SIR SIS SIT SIX SKI SKY SLY SOB SOD SON SOP SOT SOW SOY SPA SPY STY SUB SUE SUM SUN SUP '+
  'TAB TAD TAG TAN TAP TAR TAT TAX TEA TED TEE TEN THE THY TIC TIE TIN TIP TIT TOE TOM TON TOO TOP TOT TOW TOY TRY TUB TUG TUN TUT TWO '+
  'UGH URN USE '+
  'VAN VAT VET VEX VIA VIE VOW '+
  'WAD WAG WAN WAR WAS WAX WAY WEB WED WEE WET WHO WHY WIG WIN WIT WOE WOK WON WOO WOW WRY '+
  'YAK YAM YAP YAW YEA YEN YES YET YEW YIN YIP YOB YOD YOU YUK YUM '+
  'ZAP ZIP ZOO '+
  // 4-letter common
  'ABLE ABUT ACED ACES ACHE ACID ACME ACNE ACRE ACTS ADDS ADIT AEON AERO AFAR AFRO AGED AGES AGIO AGUE AHEM AIDE AIDS AILS AIMS AIRS AIRY AJAR AKIN ALAS ALBS ALEC ALES ALLY ALMA ALMS ALOE ALPS ALSO ALTO ALUM AMEN AMID AMIE AMIR AMMO AMOK AMPS AMUS ANAL AND ANEW ANIS ANTE ANTI ANTS ANUS APED APES APEX APOS APPS APSE AQUA ARCH ARCS AREA ARES ARIA ARID ARKS ARMS ARMY ARSE ARTS ARTY ARUM AUNT AURA AUTO AVER AVES AVID AVOW AWAY AWED AWES AWLS AWNS AXED AXES AXIS AXLE AYES '+
  'BABE BABY BACK BADE BADS BAGS BAIL BAIT BAKE BALD BALE BALK BALL BALM BAND BANE BANG BANK BANS BARB BARD BARE BARK BARN BARS BASE BASH BASK BATH BATS BAUD BAWD BAWL BAYS BEAD BEAK BEAM BEAN BEAR BEAT BEAU BECK BEDS BEEF BEEN BEEP BEER BEES BEET BELL BELT BEND BENT BESS BEST BETA BETS BEVY BIAS BICE BIDE BIDS BIER BIFF BIKE BILE BILK BILL BIND BINS BIOS BIRD BITE BITS BLAB BLED BLEW BLIP BLOB BLOC BLOG BLOT BLOW BLUE BLUR BOAR BOAS BOAT BODE BODS BODY BOGS BOGY BOIL BOLA BOLD BOLE BOLL BOLT BOMB BOND BONE BONG BONY BOOB BOOK BOOM BOON BOOR BOOS BOOT BORE BORN BOSS BOTH BOTS BOUT BOWL BOWS BOXY BOYS BRAG BRAN BRAS BRAT BRAY BREW BRIE BRIG BRIM BRIO BROO BROW BUBS BUCK BUDS BUFF BUGS BULB BULK BULL BUMP BUMS BUNK BUNS BURG BURL BURN BURP BURR BURY BUSH BUSK BUST BUSY BUTE BUTS BUTT BUYS BUZZ BYES BYTE '+
  'CABS CACA CADE CADS CAFE CAGE CAGY CAKE CALF CALK CALL CALM CAME CAMP CAMS CANE CANS CANT CAPE CAPO CAPS CARD CARE CARL CARP CARS CART CASE CASH CAST CATS CAVE CAWS CEDE CEES CELL CELT CENT CESS CHAP CHAR CHAT CHAW CHEF CHEW CHIC CHIN CHIP CHOP CHOW CHUB CHUG CHUM CINE CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLEF CLEW CLIP CLOD CLOG CLOP CLOT CLOY CLUB CLUE COAL COAT COBS COCA COCK COCO CODA CODE CODS COED COFS COGS COIF COIL COIN COKE COLA COLD COLE COLS COLT COMA COMB COME CONE CONK CONS COOK COOL COOP COOS COOT COPE COPS COPY CORD CORE CORK CORN CORM COSY COTE COTS COUP COVE COWL COWS COXA COZY CRAB CRAG CRAM CRAP CRAW CREW CRIB CROC CROP CROW CRUD CRUX CUBE CUBS CUDS CUED CUES CUFF CULL CULT CURB CURD CURE CURL CURS CUSP CUSS CUTE CUTS CYST '+
  'DABS DADA DADO DADS DAFT DAIS DAME DAMN DAMP DAMS DANG DANK DARE DARK DARN DART DASH DATA DATE DAUB DAWN DAYS DAZE DEAD DEAF DEAL DEAN DEAR DEBT DECK DEED DEEM DEEP DEER DEFT DEFY DELE DELI DELL DELS DEMO DEMS DENS DENT DERM DESK DEWS DEWY DIAL DICE DICK DICS DIDO DIDY DIED DIES DIET DIGS DIKE DILL DIME DIMS DINE DING DINK DINS DINT DIPS DIRE DIRT DISC DISH DISK DITS DIVA DIVE DOCK DODO DOES DOFF DOGE DOGS DOJO DOLE DOLL DOLT DOME DOMS DONA DONE DONG DOOM DOOR DOPE DOPY DORK DORM DORY DOSE DOSS DOST DOTE DOTH DOTS DOTY DOUR DOVE DOWN DOZE DOZY DRAB DRAG DRAM DRAW DRAY DREK DREW DRIP DROP DRUB DRUG DRUM DUAL DUBS DUCK DUCT DUDE DUDS DUEL DUES DUET DUFF DUGS DUKE DULL DULY DUMB DUMP DUNE DUNG DUNK DUNS DUOS DUPE DURA DURN DUSK DUST DUTY DYAD DYED DYES DYNE '+
  'EACH EARL EARN EARS EASE EAST EASY EATS EAVE EBBS ECHO ECRU ECUS EDDY EDGE EDGY EDIT EDUC EELS EGGS EGGY EGIS EGOS ELAN ELFS ELKS ELLS ELMS ELSE EMIR EMIT EMUS ENDS ENVY EONS EPEE EPIC EPOS ERAS ERGO ERGS EROS ERRS ESES ESPY EURO EVEN EVER EVES EVIL EWER EWES EXAM EXEC EXES EXIT EXPO EYED EYES EYRE '+
  'FACE FACT FADE FADS FAIL FAIN FAIR FAKE FALL FAME FANE FANG FANS FARE FARM FARO FARS FART FAST FATE FATS FAUN FAUX FAVA FAWN FAZE FEAR FEAT FEDS FEED FEEL FEES FEET FELL FELT FEND FEOD FERN FESS FETA FETE FEUD FEWS FIAT FIBS FIEF FIFE FIGS FILE FILL FILM FILO FILS FIND FINE FINK FINO FINS FIRE FIRM FIRN FIRS FISH FIST FITS FIVE FIXT FIZZ FLAB FLAG FLAK FLAP FLAT FLAW FLAX FLAY FLEA FLED FLEE FLEW FLEX FLIC FLIP FLIT FLOE FLOG FLOP FLOW FLUB FLUE FLUX FOAL FOAM FOBS FOCI FOES FOGS FOGY FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORA FORD FORE FORK FORM FORT FOUL FOUR FOWL FOXY FOYS FRAG FRAT FRAU FRAY FREE FRET FROE FROG FROM FUEL FUGS FUJI FULL FUME FUMY FUND FUNK FUNS FURL FURS FURY FUSE FUSS FUZE FUZZ '+
  'GABS GAFF GAGA GAGE GAGS GAIN GAIT GALA GALE GALL GALS GAME GAMS GAMY GANG GAOL GAPE GAPS GARB GARS GASH GASP GASS GATE GATS GAUD GAUM GAUR GAVE GAWK GAWP GAYS GAZE GEAR GECK GEED GEEK GEES GELD GELS GELT GEMS GENE GENS GENT GENU GERM GETS GEUM GHEE GIBE GIDS GIFT GIGA GIGS GILD GILL GILT GIMP GINK GINS GIRD GIRL GIRO GIRT GIST GIVE GLAD GLEE GLEN GLIB GLOB GLOM GLOP GLOW GLUE GLUG GLUM GLUT GNAR GNAT GNAW GOAD GOAL GOAS GOAT GOBO GOBS GODS GOER GOES GOFF GOGO GOLD GOLF GONE GONG GOOD GOOF GOOK GOON GOOP GOOS GORE GORP GORY GOSH GOTH GOUT GOWN GRAB GRAD GRAM GRAY GREW GREY GRID GRIM GRIN GRIP GRIT GROG GROT GROW GRUB GRUE GRUM GUAN GULF GULL GULP GULS GUMS GUNK GUNS GURU GUSH GUST GUTS GUVS GUYS GYBE GYMS GYPS GYRE GYRI GYRO GYVE '+
  'HAAF HAAR HABU HACK HADE HADJ HAED HAES HAFT HAGS HAHA HAHS HAIK HAIL HAIR HAJI HAJJ HAKE HALE HALF HALL HALM HALO HALT HAME HAMS HAND HANG HANK HAPS HARD HARE HARK HARL HARM HARP HART HASH HASP HATE HATH HATS HAUL HAVE HAWK HAWS HAYS HAZE HAZY HEAD HEAL HEAP HEAR HEAT HECK HEED HEEL HEFT HEIR HELD HELL HELM HELP HEMP HEMS HENS HERB HERD HERE HERO HERS HEWN HEWS HICK HIDE HIED HIES HIGH HIKE HILL HILT HIMS HIND HINT HIPS HIRE HISN HISS HIST HITS HIVE HOAR HOAX HOBO HOBS HOCK HODS HOED HOES HOGG HOGS HOKE HOKY HOLD HOLE HOLM HOLP HOLS HOLT HOLY HOME HOMO HOMY HONE HONG HONK HONS HOOD HOOF HOOK HOOP HOOT HOPE HOPS HORA HORN HOSE HOST HOTS HOUR HOUT HOVE HOWE HOWK HOWL HOWS HOYS HUBS HUED HUES HUFF HUGE HUGS HULA HULK HULL HUMP HUMS HUNG HUNK HUNS HUNT HURL HURT HUSH HUSK HUTS HYED HYES HYLA HYMN HYPE HYPS '+
  'IAMB IBEX IBIS ICED ICES ICHS ICKY ICON IDEA IDES IDLE IDLY IDOL IFFY IGLU ILKS ILLS IMAM IMPI IMPS INBY INCH INFO INIA INKS INKY INNS INTO IONS IOTA IRED IRES IRIS IRKS IRON ISLE ITCH ITEM IWIS '+
  'JABS JACK JADE JAGS JAIL JAKE JAMB JAMS JANE JAPE JARL JARS JATO JAUK JAVA JAWS JAYS JAZZ JEAN JEED JEEP JEER JEES JEEZ JEFE JEHU JELL JERK JESS JEST JETE JETS JEUX JEWS JIAO JIBB JIBE JIBS JIFF JIGS JILL JILT JIMP JINK JINN JINS JINX JISM JIVE JIVY JOBS JOCK JOES JOEY JOGS JOHN JOIN JOKE JOKY JOLE JOLT JOSH JOSS JOTA JOTS JOWL JOYS JUBA JUBE JUCO JUDO JUGA JUGS JUJU JUKE JUMP JUNE JURA JURY JUST JUTE JUTS '+
  'KAAS KABS KADI KAFS KAGU KAIL KAIN KAKA KAKI KALE KAMI KANA KANE KAON KAPA KAPH KAPS KARN KART KATA KATS KAYO KAYS KBAR KEAS KECK KEEF KEEK KEEL KEEN KEEP KEET KEFS KEGS KELP KEMP KENO KENS KENT KEPI KEPS KEPT KERB KERF KERN KETO KEYS KHAF KHAN KHAT KHET KICK KIDS KIEF KIER KIFS KILL KILN KILO KILP KILT KINA KIND KINE KING KINK KINO KINS KIPS KIRK KIRN KIRS KISS KIST KITE KITH KITS KIVA KIWI KLIK KLUG KNAG KNAP KNAR KNEE KNEW KNIT KNOB KNOP KNOT KNOW KNUR KOAN KOAS KOBO KOBS KOEL KOHL KOI KOJI KOLO KOND KOOK KOPH KOPS KORA KORE KOSS KOTO KRAT KRIS KUDO KUDU KUES KUFI KUNA KUNE KURU KVAS KYAK KYAT KYES '+
  // common 5-letter
  'ABACK ABAFT ABASE ABASH ABATE ABBEY ABBOT ABHOR ABIDE ABLED ABODE ABORT ABOUT ABOVE ABUSE ABYSS ACORN ACRID ACTED ACTOR ACUTE ADAGE ADAPT ADDER ADEPT ADIEU ADMIN ADMIT ADOBE ADOPT ADORE ADORN ADULT AFFIX AFIRE AFOOT AFOUL AFTER AGAIN AGAPE AGATE AGENT AGILE AGING AGLOW AGONY AGREE AHEAD AIDED AIDES AIMED AISLE ALARM ALBUM ALERT ALGAE ALIAS ALIBI ALIEN ALIGN ALIKE ALIVE ALLAY ALLEY ALLOT ALLOW ALLOY ALOFT ALOHA ALONE ALONG ALOOF ALOUD ALPHA ALTAR ALTER AMASS AMAZE AMBER AMBLE AMEND AMIGO AMISS AMITY AMONG AMOUR AMPLE AMPLY AMUSE ANGEL ANGER ANGLE ANGRY ANGST ANIME ANKLE ANNEX ANNOY ANNUL ANODE ANTIC ANVIL AORTA APART APHID APING APNEA APPLE APPLY APRON APTLY ARBOR ARDOR ARENA ARGUE ARISE ARMOR AROMA AROSE ARRAY ARROW ARSON ARTSY ASCOT ASHEN ASIDE ASKED ASKEW ASSAY ASSET ATLAS ATOLL ATOMS ATONE ATTIC AUDIO AUDIT AUGUR AUNTY AVAIL AVERT AVIAN AVOID AWAIT AWAKE AWARD AWARE AWASH AWFUL AWOKE AXIAL AXIOM AXION AZURE '+
  'BACON BADGE BADLY BAGEL BAGGY BAKER BALDY BALER BALMY BANAL BANJO BARGE BARON BASAL BASED BASIC BASIL BASIN BASIS BASTE BATCH BATED BATHE BATON BATTY BAWDY BAYOU BEACH BEADY BEARD BEAST BEEFY BEFIT BEGAN BEGET BEGIN BEGUN BEIGE BEING BELCH BELIE BELLE BELLY BELOW BENCH BERET BERRY BERTH BESET BETEL BEVEL BEZEL BIBLE BICEP BIDDY BIGOT BILGE BILLY BINGE BINGO BIOME BIRCH BIRDS BIRTH BISON BITCH BITES BITTY BLACK BLADE BLAME BLAND BLANK BLARE BLAST BLAZE BLEAK BLEAT BLEED BLEND BLESS BLIMP BLIND BLINK BLISS BLITZ BLOAT BLOCK BLOKE BLOND BLOOD BLOOM BLOWN BLUES BLUFF BLUNT BLURB BLURT BLUSH BOARD BOAST BOBBY BOGEY BOGGY BOILS BOLAS BOLTS BONES BONGO BONNY BONUS BOOBY BOOKS BOOST BOOTH BOOTS BOOTY BOOZE BOOZY BORAX BORED BORES BORNE BOSOM BOSSY BOTCH BOUGH BOULE BOUND BOWED BOWEL BOXED BOXER BRACE BRAID BRAIN BRAKE BRAND BRASH BRASS BRAVE BRAVO BRAWL BRAWN BREAD BREAK BREED BRIAR BRIBE BRICK BRIDE BRIEF BRINE BRING BRINK BRINY BRISK BROAD BROIL BROKE BROOD BROOK BROOM BROTH BROWN BRUNT BRUSH BRUTE BUDDY BUDGE BUGGY BUGLE BUILD BUILT BULGE BULKY BULLS BULLY BUMPY BUNCH BUNNY BURLY BURNT BURST BUSED BUSHY BUTCH BUTTE BUYER BYWAY '+
  'CABAL CABIN CABLE CACAO CACHE CACTI CADDY CADET CAGED CAIRN CAMEL CAMEO CANAL CANAS CANDY CANNY CANOE CANON CAPED CAPER CAPON CARAT CARDS CARGO CAROB CAROL CARRY CARTS CARVE CASED CASES CASTE CATCH CATER CATTY CAULK CAUSE CAVED CAVES CEASE CEDAR CELLO CHAFE CHAFF CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHAPS CHARD CHARM CHART CHASE CHASM CHEAP CHEAT CHECK CHEEK CHEER CHESS CHEST CHEWY CHICK CHIDE CHIEF CHILD CHILI CHILL CHIME CHINA CHIPS CHIRP CHOCK CHOIR CHOKE CHORD CHORE CHOSE CHUCK CHUMP CHUNK CHURN CHUTE CIDER CIGAR CINCH CIRCA CIRCLE CIRCUS CITED CITES CIVIC CIVIL CLACK CLAIM CLAMP CLANG CLANK CLASH CLASP CLASS CLEAN CLEAR CLEAT CLEFT CLERK CLICK CLIFF CLIMB CLINE CLING CLINK CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOUT CLOVE CLOWN CLUCK CLUED CLUES CLUMP CLUNG COACH COAST COBRA COCOA COLLY COLON COLOR COMET COMFY COMIC COMMA CONCH CONDO CONIC CORAL CORER CORGI CORKY CORNY COUCH COUGH COULD COUNT COURT COVEN COVER COVET COVEY COWED COWER COYLY CRACK CRAFT CRAMP CRANE CRANK CRASH CRASS CRATE CRAVE CRAWL CRAZE CRAZY CREAK CREAM CREDO CREED CREEK CREEP CREPE CREPT CRESS CREST CREWS CRICK CRIED CRIER CRIES CRIME CRIMP CRISP CROAK CROCK CROFT CRONE CRONY CROOK CROSS CROUP CROWD CROWN CRUDE CRUEL CRUMB CRUSH CRUST CRYPT CUBED CUBES CUBIC CURDS CURED CURES CURIO CURLS CURLY CURRY CURSE CURVE CURVY CUTEY CYBER CYCLE CYNIC '+
  'DADDY DAILY DAIRY DAISY DALLY DANDY DATED DATES DATUM DAUNT DAZED DEALT DEATH DEBAR DEBIT DEBTS DEBUG DEBUT DECAF DECAL DECAY DECOR DECOY DECRY DEEDS DEFER DEIGN DEITY DELAY DELIS DELTA DELVE DEMON DEMUR DENIM DENSE DEPOT DEPTH DERBY DETER DEUCE DEVIL DIARY DICED DICES DICEY DICKY DIETS DIGIT DIMLY DINER DINGO DINGY DIRGE DIRTY DISCO DITCH DITTO DITTY DIVAN DIVED DIVES DIVVY DIZZY DODGE DODGY DOING DOLLY DONOR DONUT DOPED DOPES DOPEY DOUBT DOUGH DOWEL DOWNY DOWRY DOZED DOZEN DRAFT DRAIN DRAKE DRAMA DRANK DRAPE DRAWL DRAWN DRAWS DREAD DREAM DRESS DREWS DRIED DRIER DRIFT DRILL DRINK DRIPS DRIVE DROIT DROLL DRONE DROOL DROOP DROSS DROVE DROWN DRUGS DRUNK DRYER DUCHY DUCKS DULLY DUMMY DUMPS DUMPY DUNCE DUSKY DUSTY DUTCH DWARF DWELL DWELT DYING '+
  'EAGER EAGLE EARLY EARNS EARTH EASED EASEL EASES EATEN EATER EBBED EBONY EDGED EDGES EDICT EDIFY EERIE EGRET EIGHT EIGHTY EJECT EKING ELATE ELBOW ELDER ELECT ELEGY ELFIN ELIDE ELITE ELOPE ELUDE ELVES EMAIL EMBED EMBER EMCEE EMPTY ENACT ENDED ENDOW ENEMA ENEMY ENJOY ENNUI ENSUE ENTER ENTRY ENVOY EPOCH EPOXY EQUAL EQUIP ERASE ERECT ERODE ERRED ERROR ERUPT ESSAY ESTER ETHER ETHIC ETHOS EUROS EVADE EVENT EVERY EVICT EVILS EVOKE EXACT EXALT EXCEL EXERT EXILE EXIST EXITS EXPEL EXTOL EXTRA EXULT EYING '+
  'FABLE FACED FACES FACET FAINT FAIRS FAIRY FAITH FAKED FAKER FAKES FALLS FALSE FAMED FANCY FANGS FANNY FAVOR FEAST FECAL FEIGN FELLA FELON FEMME FEMUR FENCE FERAL FERNS FERRY FETAL FETCH FETED FEVER FEWER FIBER FICHE FICUS FIELD FIEND FIERY FIFTH FIFTY FIGHT FILCH FILED FILES FILET FILLY FILMS FILMY FILTH FINAL FINCH FINDS FINED FINER FINES FIORD FIRED FIRES FIRMS FIRST FISHY FIVES FIXED FIXER FIZZY FJORD FLACK FLAIL FLAIR FLAKE FLAKY FLAME FLANK FLARE FLASH FLASK FLATS FLAWS FLEAS FLECK FLEET FLESH FLIED FLIER FLIES FLING FLINT FLIRT FLOAT FLOCK FLOES FLOGS FLOOD FLOOR FLOPS FLORA FLOSS FLOUR FLOUT FLOWN FLOWS FLUFF FLUID FLUKE FLUNG FLUNK FLUSH FLUTE FLYER FOAMY FOCAL FOCUS FOGGY FOLIC FOLIO FOLKS FONDU FOODS FOOLS FOOTS FORAY FORCE FORGE FORGO FORKS FORMS FORTE FORTH FORTS FORTY FORUM FOUND FOUNT FOURS FOWLS FOYER FRACK FRAIL FRAME FRANK FRAUD FREAK FREED FREER FRESH FRIAR FRIED FRIES FRILL FRISK FRITZ FROCK FROGS FROND FRONT FROST FROTH FROWN FROZE FRUIT FUDGE FUELS FULLY FUNGI FUNKY FUNNY FURRY FUROR FURRY FURZY FUSED FUSES FUSSY FUZZY '+
  'GABBY GAFFE GAILY GAINS GAMED GAMES GAMMA GAMUT GASES GASSY GATED GATES GAUDY GAUGE GAUNT GAUZE GAUZY GAVEL GAWKS GAWKY GAZED GAZES GAZER GEARS GEEKS GEEKY GEESE GENES GENIE GENRE GENTS GENUS GEODE GERMS GETUP GHOST GHOUL GIANT GIDDY GIRTH GIVEN GIVER GIVES GLADE GLADLY GLAND GLANS GLARE GLASS GLAZE GLEAM GLEAN GLEES GLIDE GLINT GLOAT GLOBE GLOOM GLORY GLOSS GLOVE GLOWS GLUED GLUES GLUEY GNARL GNASH GOADS GOALS GOATS GODLY GOERS GOING GOLEM GOODY GOOEY GOOFY GOONS GOOSE GORED GORGE GOUGE GOURD GRACE GRADE GRAFT GRAIL GRAIN GRAMS GRAND GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAZE GREAT GREED GREEN GREET GRIEF GRILL GRIME GRIMY GRIND GRINS GRIPE GRIPS GROAN GROIN GROOM GROPE GROSS GROUP GROUT GROVE GROWL GROWN GROWS GRUEL GRUFF GRUMP GRUNT GUARD GUAVA GUESS GUEST GUIDE GUILD GUILE GUILT GUISE GULCH GULLS GULLY GULPS GUMBO GUMMY GUPPY GUSTO GUSTS GUSTY GUTSY GYPSY '+
  'HABIT HADES HADJS HAIKU HAILS HAIRS HAIRY HALOS HALVE HANDS HANDY HAPPY HARDY HAREM HARPS HARPY HARRY HARSH HASTE HASTY HATCH HATED HATER HATES HAUNT HAVEN HAVES HAWKS HAZEL HEADS HEADY HEARD HEARS HEART HEATS HEAVE HEAVY HEDGE HEFTY HEIGH HEIRS HEIST HELIX HELLO HELLS HELPS HENCE HERBS HERDS HERON HERTZ HEWN HICKS HIDED HIDES HIGHS HIKER HIKES HILLS HILLY HILTS HINGE HINTS HIPPO HIPPY HIRED HIRER HIRES HITCH HIVED HIVES HOARD HOARS HOARY HOBBY HOGAN HOIST HOLDS HOLED HOLES HOLEY HOLLY HOMED HOMER HOMES HOMEY HONED HONES HONEY HONKS HONOR HOOCH HOODS HOOFS HOOKS HOOKY HOOPS HOOTS HOPED HOPES HORDE HORNS HORNY HORSE HOSED HOSES HOSTS HOTEL HOTLY HOUND HOURS HOUSE HOVEL HOVER HOWDY HOWLS HUBBY HUFFY HULLS HUMAN HUMID HUMPH HUMPS HUMUS HUNCH HUNKS HUNTS HURLS HURRY HURTS HUSKS HUSKY HUSSY HUTCH HYDRA HYDRO HYENA HYMEN HYMNS HYPES HYPOS '+
  // 6-letter
  'ABDUCT ABHORS ABIDED ABIDES ABJECT ABLAZE ABOARD ABODES ABOUND ABRUPT ABSENT ABSORB ABSURD ABUSED ABUSER ABUSES ACCEDE ACCENT ACCEPT ACCESS ACCORD ACCRUE ACCUSE ACHING ACIDIC ACIDLY ACORNS ACTING ACTION ACTIVE ACTORS ACTUAL ACUITY ACUMEN ADAGES ADAPTS ADDICT ADDING ADDUCE ADHERE ADIPIC ADJURE ADJUST ADMIRE ADMITS ADOBES ADOPTS ADORED ADORES ADORNS ADRIFT ADROIT ADULTS ADVENT ADVERB ADVERT ADVICE ADVISE AERATE AERIAL AERIES AFFAIR AFFECT AFFIRM AFFIX AFFORD AFRAID AGATES AGEISM AGENCY AGENDA AGENTS AGGIES AGHAST AGILE AGING AGINGS AGLARE AGONIE AGREED AGREES ALBUMS ALCOVE ALIENS ALIGHT ALIGNS ALIKES ALIVES ALLAYS ALLEGE ALLEYS ALLIED ALLIES ALLOTS ALLOWS ALLOYS ALLUDE ALMOND ALMOST ALPACA ALTARS ALWAYS AMAZED AMAZES AMBERS AMBITS AMENDS AMIDST AMOEBA AMONGS AMOUNT AMPERE AMULET ANCHOR ANCIENT ANCLES ANEMIA ANGELS ANGERS ANGLER ANGLES ANGLED ANGORA ANGRY ANIMAL ANKLES ANNALS ANNEAL ANNEXES ANNOYS ANNUAL ANODES ANSWER ANTHEM ANTICS ANTLER ANVILS ANYONE ANYWAY APATHY APEMAN APHIDS APIECE APPEAL APPEAR APPEND APPLES APPOSE APROPOS APRONS APTEST ARBORS ARCADE ARCANE ARCHED ARCHER ARCHES ARCING ARDENT ARDOUR ARDUOUS ARGUED ARGUES ARGUER ARIGHT ARISEN ARMADA ARMAND ARMIES ARMING ARMOIRE ARMORS ARMORY AROMAS AROUND AROUSE ARRAYS ARREAR ARREST ARRIVE ARROWS ARSENAL ARSONS ARTERY ARTFUL ARTICLE ARTIST ASCEND ASCENT ASHORE ASKING ASLEEP ASPECT ASPEN ASPIRE ASSAIL ASSAYS ASSENT ASSERT ASSESS ASSETS ASSIGN ASSIST ASSIZE ASSORT ASSUME ASSURE ASTERN ASTHMA ASTRAL ASTRAY ASYLUM ATHENS ATHLETE ATONIC ATRIUM ATTACH ATTACK ATTAIN ATTAR ATTEND ATTEST ATTICS ATTIRE ATTUNE AUBURN AUGURS AUGUST AUNTIE AURORA AUTHOR AUTISM AUTUMN AVATAR AVENGE AVENUE AVERSE AVIARY AVOIDS AWAITS AWAKEN AWARDS AXIOMS '+
  'BABIES BABOON BACKED BACKER BACKUP BADGER BADGES BADLAND BAFFLE BAGELS BAGGIE BAILED BAKERS BAKERY BAKING BALKED BALKS BALLAD BALLET BALLOT BALMY BANALITY BANANA BANDED BANDIT BANGED BANISH BANKED BANKER BANNED BANNER BANTER BARBED BARBEL BARBER BARELY BARFED BARGED BARGES BARING BARKED BARKER BARLEY BARMEN BARNEY BARONS BARRED BARREL BARREN BARRIO BARROW BARTER BASELY BASHED BASHES BASICS BASILS BASINS BASKED BASKET BASSES BASSET BATHED BATHES BATTER BATTLE BAUBLE BAWDIER BAWLED BAWLER BAWLS BAZAAR BEACON BEADED BEAGLE BEAKED BEAKER BEAMED BEANED BEANIE BEAREN BEARDS BEARER BEATEN BEATER BEAUTS BEAUTY BEAVER BECAME BECKON BECOME BEDDED BEDLAM BEEFED BEETLE BEFALL BEFELL BEFITS BEFOG BEFORE BEGETS BEGGAR BEGGED BEGINS BEHALF BEHAVE BEHEAD BEHELD BEHIND BEINGS BELDAM BELIEF BELIES BELLOW BELONG BELONGS BELOVED BELOWS BELTED BEMUSE BENDER BENEATH BENIGN BENUMB BEREFT BERETS BERETS BERTHS BESEECH BESIDE BESTOW BETAKE BETIDE BETONS BETRAY BETTER BETTOR BEWAIL BEWARE BEYOND BIALYS BIASES BICEPS BICORN BICYCLE BIDDER BIFOLD BIFOLD BIGGER BIKING BILGES BILLED BILLET BILLOW BIMETAL BINDER BINGES BIOGEN BIOMASS BIRDIE BIRTHDAY BISCUIT BISHOP BISTROS BITCH BITTEN BITTER BIZARRE BLACKS BLADES BLAMED BLAMES BLANCH BLANDER BLANKS BLARED BLARES BLASTS BLAZED BLAZES BLAZON BLEACH BLEATS BLEEDS BLENDS BLESS BLIGHT BLINDS BLINKS BLISS BLITZ BLOATS BLOCKS BLOKES BLONDE BLONDES BLOODY BLOOMS BLOTCH BLOUSE BLOWER BLUELY BLUETS BLUFFS BLUISH BLURBS BLURRY BLURTS BLUSHY BOARDS BOASTS BOATED BOATER BOBBED BOBBIN BOBBED BODICE BODIES BODIED BOGGED BOGGLE BOILED BOILER BOLDER BOLDLY BOLERO BOLTED BOMBED BOMBER BONBON BONDED BONERS BONIER BONITO BONKED BONNET BOOBED BOOGIE BOOING BOOKED BOOKER BOOMED BOOMER BOOSTS BOOTED BOOTEE BOOTIE BOOTIES BOOTY BOOZED BOOZER BOOZES BORAGE BORDER BORERS BORING BORROW BOSKET BOSSED BOSSES BOTANY BOTCHED BOTCHES BOTHER BOTTLE BOTTOM BOUGHS BOUGHT BOUNCE BOUNCY BOUNDS BOUNTY BOURNE BOURSE BOUTS BOVINE BOWELS BOWERY BOWERS BOWING BOWLED BOWLER BOWWOW BOXCAR BOXERS BOXING BOYARD BOYISH BRACED BRACER BRACES BRAINS BRAINY BRAISE BRAKED BRAKES BRANCH BRANDS BRANDY BRASH BRASSY BRAVED BRAVER BRAVES BRAVOS BRAWLS BRAWNY BRAYED BRAZEN BRAZIL BREACH BREAD BREAKS BREAST BREATH BREEDS BREEZE BREEZY BREWED BREWER BRIARS BRIBED BRIBES BRIDGE BRIDLE BRIEFS BRIERS BRIGHT BRIMMED BRINDLE BRINDY BRINED BRINED BRINGS BRITCH BROACH BROAD BROCADE BROCCOLI BROILS BROKEN BROKER BRONZE BROODS BROOKS BROOM BROTHS BROWNS BROWSE BRUINS BRUISE BRUNCH BRUSHED BRUTAL BRUTE BUBBLE BUCKED BUCKER BUCKET BUCKLE BUDDED BUDDHA BUDDIES BUDGET BUFFED BUFFER BUFFET BUGLER BUGLES BULGED BULGES BULLET BUMPER BUNCHES BUNDLE BUNGEE BUNKED BUNKER BUNNIES BUOYED BURDEN BUREAU BURGER BURIAL BURIED BURLAP BURNED BURNER BURRED BURROW BURSTS BUSHED BUSIER BUSILY BUSINESS BUSTED BUSTLE BUTTER BUTTES BUTTON BUYERS BUYING BUZZED BUZZES BYLINE BYPASS BYWAYS '+
  'MARKET MASTER MATTER MATURE MEDIUM MEMBER MEMORY MENTAL MERELY MERGER MIDDLE MIGHT MINGLE MINUTE MODERN MODEST MODIFY MODULE MOMENT MOSTLY MOTHER MOTION MOVING MUSEUM MUTUAL MYSTERY MONSTER '+
  'NATION NATIVE NATURE NEARBY NEARLY NEEDED NEITHER NETWORK NORMAL NOTICE NOTION NUMBER '+
  'OBJECT OBTAIN OCCUPY OCCUR OCEAN OFFEND OFFICE OFTEN ONLINE OPENED OPENLY OPTION ORANGE ORIGIN OUTPUT '+
  'PACKED PALACE PARENT PARTLY PATENT PATROL PEOPLE PERIOD PERMIT PERSON PHRASE PICKED PICKUP PLANET PLAYED PLAYER PLEASE POETIC POLICE POLICY POLISH POWERS PRAISE PRAYER PRETTY PRIEST PRISON PRIZE PROFIT PROPER PROTECT PUBLIC PURELY PURPLE PURSUE '+
  'QUARRY QUARTZ QUEERS QUIVER QUICKLY '+
  'RARELY RATHER RATING RATTLE REBORN RECALL RECIPE REFUGE REGARD REGION REJECT REMAIN REMEDY REMIND REMOTE REMOVE REPAIR REPEAT REPLY REPORT RESCUE RESULT RESUME RETAIL RETAIN RETIRE RETURN REVEAL REVIEW REWARD RIDING RISING RITUAL ROLLED ROTATE ROUGHLY ROUTER '+
  'SACRED SAFELY SAILED SAILOR SAMPLE SAVING SAYING SCHEME SCHOOL SCORE SCREEN SEARCH SEASON SECOND SECRET SECTOR SECURE SEEING SEEKER SELECT SELLER SENIOR SERIES SERVER SETTLE SEVERE SEXUAL SHADOW SHAKEN SHAPES SHARED SHARPER SHIELD SHIVER SIMPLE SIMPLY SINGER SINGLE SISTER SKETCH SLIGHT SLIMLY SMALLS SOCCER SOCIAL SOCIETY SOFTLY SOLELY SOLEMN SOLVED SOMBER SOONER SORROW SPARED SPEAKER SPEECH SPIRIT SPONGE SPORTS SPREAD SPRING SQUARE STABLE STATED STATIC STATUE STATUS STEADY STEAMY STEPPE STICKY STOLEN STORE STRAIN STREAM STREET STRESS STRICT STRING STROKE STRONG STRUCK STUDIO STUPID SUBJECT SUBMIT SUDDEN SUFFER SUGAR SUMMER SUMMIT SUNDAY SUNRISE SUNSET SUPPLY SUPPORT SURELY SURETY SURVEY SWITCH SYMBOL SYSTEM'
).split(/\s+/).filter(Boolean));

function valueOf(letter) { return LETTER_VALUES[letter] || 0; }

function makeTile(letter, { choiceAlt = null, mult = 1 } = {}) {
  return { id: Math.random().toString(36).slice(2,9), letter, choiceAlt, mult };
}

function drawTiles(count, { choiceCount = 0 } = {}) {
  const tiles = [];
  for (let i = 0; i < count; i++) {
    const l = LETTER_BAG[Math.floor(Math.random() * LETTER_BAG.length)];
    // 15% chance doubled (prefers 5+), 5% tripled
    const val = valueOf(l);
    let mult = 1;
    if (val >= 5 && Math.random() < 0.25) mult = 2;
    else if (Math.random() < 0.08) mult = 2;
    if (mult === 1 && Math.random() < 0.04) mult = 3;
    tiles.push(makeTile(l, { mult }));
  }
  // Replace up to choiceCount random tiles with choice tiles
  const positions = [...Array(tiles.length).keys()].sort(() => Math.random() - 0.5);
  for (let i = 0; i < Math.min(choiceCount, tiles.length); i++) {
    const pair = CHOICE_PAIRS[Math.floor(Math.random() * CHOICE_PAIRS.length)];
    const [a, b] = Math.random() < 0.5 ? pair : [pair[1], pair[0]];
    tiles[positions[i]] = makeTile(a, { choiceAlt: b, mult: 1 });
  }
  return tiles;
}

// Given a word (string) and available tiles (array), return best assignment or null
function validateWord(word, tiles) {
  const letters = word.toUpperCase().split('');
  if (letters.length < 2 || letters.length > 7) return null;
  if (!DICT.has(word.toUpperCase())) return null;

  // greedy: try to match each needed letter to an available tile
  const used = new Set();
  const assignment = [];
  for (const L of letters) {
    let found = -1;
    for (let i = 0; i < tiles.length; i++) {
      if (used.has(i)) continue;
      const t = tiles[i];
      if (t.letter === L || t.choiceAlt === L) {
        found = i;
        // prefer exact match over alt
        if (t.letter === L) break;
      }
    }
    if (found === -1) return null;
    used.add(found);
    assignment.push({ tile: tiles[found], chosen: L });
  }
  return assignment;
}

function scoreWord(word, tiles) {
  const assign = validateWord(word, tiles);
  if (!assign) return { valid: false, score: 0, breakdown: [] };
  let total = 0;
  const breakdown = assign.map(({ tile, chosen }) => {
    const base = valueOf(chosen);
    const final = base * tile.mult;
    total += final;
    return { letter: chosen, base, mult: tile.mult, final };
  });
  let bonus = 0;
  if (assign.length === 7) { bonus = 10; total += 10; }
  return { valid: true, score: total, breakdown, bonus, word: word.toUpperCase() };
}

// AI: try to find a decent word given tiles
function findBestWord(tiles, { maxTries = 200 } = {}) {
  // Try some common short words first, then progressively
  const letterSet = tiles.flatMap(t => t.choiceAlt ? [t.letter, t.choiceAlt] : [t.letter]);
  // Score all dictionary words that could possibly be made - filter by letter availability
  let best = null;
  let bestScore = 0;
  let count = 0;
  for (const w of DICT) {
    if (w.length < 2 || w.length > 7) continue;
    // quick rejection: all letters present in letterSet
    const need = {};
    for (const c of w) need[c] = (need[c] || 0) + 1;
    // count available for each letter (considering choice tiles)
    let possible = true;
    // Simple check: for each required letter, we must have enough tiles that include it
    // This is an approximation; validateWord is the real check
    const result = scoreWord(w, tiles);
    if (result.valid && result.score > bestScore) {
      best = result;
      bestScore = result.score;
    }
    count++;
    if (count > 3000 && best) break;
  }
  return best;
}

Object.assign(window, {
  LETTER_VALUES, LETTER_BAG, CHOICE_PAIRS, DICT,
  valueOf, makeTile, drawTiles, validateWord, scoreWord, findBestWord,
});
