/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsCodeRouteImport } from './routes/rooms.$code'
import { Route as ResultsCodeRouteImport } from './routes/results.$code'
import { Route as DevTileShowcaseRouteImport } from './routes/dev.tile-showcase'
import { Route as DevTableShowcaseRouteImport } from './routes/dev.table-showcase'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as AdminTracesRouteImport } from './routes/admin/traces'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsCodeRoute = RoomsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RoomsRoute,
} as any)
const ResultsCodeRoute = ResultsCodeRouteImport.update({
  id: '/results/$code',
  path: '/results/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTileShowcaseRoute = DevTileShowcaseRouteImport.update({
  id: '/dev/tile-showcase',
  path: '/dev/tile-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTableShowcaseRoute = DevTableShowcaseRouteImport.update({
  id: '/dev/table-showcase',
  path: '/dev/table-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTracesRoute = AdminTracesRouteImport.update({
  id: '/admin/traces',
  path: '/admin/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traces': typeof AdminTracesRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/dev/table-showcase': typeof DevTableShowcaseRoute
  '/dev/tile-showcase': typeof DevTileShowcaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traces': typeof AdminTracesRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/dev/table-showcase': typeof DevTableShowcaseRoute
  '/dev/tile-showcase': typeof DevTileShowcaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traces': typeof AdminTracesRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/dev/table-showcase': typeof DevTableShowcaseRoute
  '/dev/tile-showcase': typeof DevTileShowcaseRoute
  '/results/$code': typeof ResultsCodeRoute
  '/rooms/$code': typeof RoomsCodeRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/verify-email'
    | '/admin/stats'
    | '/admin/traces'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/dev/table-showcase'
    | '/dev/tile-showcase'
    | '/results/$code'
    | '/rooms/$code'
    | '/rooms/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/verify-email'
    | '/admin/stats'
    | '/admin/traces'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/dev/table-showcase'
    | '/dev/tile-showcase'
    | '/results/$code'
    | '/rooms/$code'
    | '/rooms'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/verify-email'
    | '/admin/stats'
    | '/admin/traces'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/dev/table-showcase'
    | '/dev/tile-showcase'
    | '/results/$code'
    | '/rooms/$code'
    | '/rooms/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTracesRoute: typeof AdminTracesRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DevTableShowcaseRoute: typeof DevTableShowcaseRoute
  DevTileShowcaseRoute: typeof DevTileShowcaseRoute
  ResultsCodeRoute: typeof ResultsCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/$code': {
      id: '/rooms/$code'
      path: '/$code'
      fullPath: '/rooms/$code'
      preLoaderRoute: typeof RoomsCodeRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/results/$code': {
      id: '/results/$code'
      path: '/results/$code'
      fullPath: '/results/$code'
      preLoaderRoute: typeof ResultsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/tile-showcase': {
      id: '/dev/tile-showcase'
      path: '/dev/tile-showcase'
      fullPath: '/dev/tile-showcase'
      preLoaderRoute: typeof DevTileShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/table-showcase': {
      id: '/dev/table-showcase'
      path: '/dev/table-showcase'
      fullPath: '/dev/table-showcase'
      preLoaderRoute: typeof DevTableShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/traces': {
      id: '/admin/traces'
      path: '/admin/traces'
      fullPath: '/admin/traces'
      preLoaderRoute: typeof AdminTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoomsRouteChildren {
  RoomsCodeRoute: typeof RoomsCodeRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsCodeRoute: RoomsCodeRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTracesRoute: AdminTracesRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DevTableShowcaseRoute: DevTableShowcaseRoute,
  DevTileShowcaseRoute: DevTileShowcaseRoute,
  ResultsCodeRoute: ResultsCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
